# Site settings
title: Data Motivated
description: A Data Science Portfolio and Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Colin Bradley
user_description: "Welcome to my website! I am super excited to share anything and everything I find interesting with the world. 
On this site I'll list some fun portfolio projects on everything from NFL analytics to book recommender systems and everything in between. 
I'll also write some blog posts on Machine Learning, Statistics, Math and Physics! So have a poke around and please feel free to email me with
questions, comments, or if you just want to chat about these topics that I'm so passtionate about. "
user_title: Data Scientist
email: c.bradley.do@gmail.com
linkedin: 
  username: colin-bradley-data-motivated
github:
  username: ColinB19             # change to your github username

social:
  name: Colin Bradley                 # it will shows as the copyright owner in Footer
  email: c.bradley.do@gmail.com            # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.linkedin.com/in/colin-bradley-data-motivated
    - https://twitter.com/data_motivated    # change to your twitter homepage
    - https://github.com/ColinB19      # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
