# Site settings
title: Data Motivated
description: A Data Science Portfolio and Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Colin Bradley
user_description: Welcome to my website! Here I will discuss my journey through data science,
  physics concepts I find interesting, and anything else I think
  people would enjoy reading.
user_title: Data Scientist
email: c.bradley.do@gmail.com
linkedin: 
  username: colin-bradley-data-motivated
github:
  username: ColinB19             # change to your github username


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
