# Site settings
title: Data Motivated
description: A Data Science Portfolio and Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Colin Bradley
user_description: Hi there! I am a Data Scientist striving to answer hard questions with data. 
user_title: Data Scientist
email: c.bradley.do@gmail.com
linkedin_username: colin-bradley-data-motivated
github_username:  colinb19
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
